
@startuml
class Modeselektor
class Historian
class Zoneherd
class Valiant
class Maestro


object hist

object eval

map zoneherd {
    suggest => zone
    result  => zone

}

map agents {
   suggestAgent => Agent
   editAgent => Agent
   resultAgent => Agent
   sessionAgent => Agent
}

map maestro {
   agents *--> agents
   zoneBox => Mailbox
}

map modeS {
   zones *--> zoneherd
   hist  *--> hist
   maestro *--> maestro
   eval    *--> eval
}

Modeselektor --|> modeS : new
Zoneherd --|> zoneherd : new
Historian --|> hist : new
Valiant --|> eval : new
Maestro --|> maestro : new
@enduml
